roms/switch/readme.md
=> Added switch folder to roms

install.sh
=> Fix SD Card detection and references to mmcblk0p1

install.sh
fix true false options
fix rabezels options
fix $filesave variable
=> Fix Autosave option and RABezels options

install.sh
Also, make passwd search for current user regardless of name. useful not-decks.
#79
=> Remove Hardcoded Saves Path

install.sh
allows any fs as long as it's writable and can support symlink.
thanks @popsUlfr
=> use popsUlfr's method to test sd card

install.sh
allows it to function for users with multiple flathub entries
=> add system to installs

configs/steam-rom-manager/userData/userConfigurations.json
fix parser and category to PrimeHack not PrimeHacks
=> Adjust Steam Rom Parser types

install.sh, tools/chdconv/chddeck.sh
Fits in with https://github.com/dragoonDorise/EmuDeck/pull/92
=> Chd - Fix some hardcoded paths

tools/chdconv/chddeck.sh
Warn the user if there's nothing to convert
=> Add no roms message

configs/app.xemu.xemu/data/xemu/xemu/xemu.toml, install.sh
Corrected some things so that all of the required xemu files are user accessible.
=> Update the Xemu.toml.

configs/net.rpcs3.RPCS3/config/rpcs3/vfs.yml, configs/steam-rom-manager/userData/userConfigurations.json, install.sh
update install to change the dev_hdd0 location.
Migrate dev_hdd0 to saves directory.
=> Add rpcs3 to save migration.

configs/cemu/cemu.sh, configs/emulationstation/custom_systems/es_systems.xml, install.sh
Adds in the necessary files and a script to run Cemu.exe through Proton
=> Add Cemu (Proton) to ES DE

install.sh
downloads the file leon makes, greps for the url, uses the url, deletes the file.
=> Dynamic emulation station pull

tools/chdconv/chddeck.sh
this warns the user they may lose things.
=> Chd improvements

install.sh
=> Add more info to powertools dialog

install.sh
Found the launching problem.
Thanks to Aido on Discord for help pinning the issue down.
=> Fix sed for cemu.sh APPPATH

install.sh
trying for least priv with these overrides
- xemu
- pcsx2
=> More flatpak override updates

install.sh
New PowerTools update, this updates the tag to v0.4.0
https://github.com/NGnius/PowerTools/releases/tag/v0.4.0
=> Update PowerTools to v0.4.0

install.sh
=> replace all zenity redirects

install.sh
Linting using Shellcheck : https://www.shellcheck.net/
No feature change, only using bash style coding.
=> Fixes using Shellcheck

install.sh
Reverts dragoonDorise/EmuDeck#166
broke some strings.
=> Revert "Fixes using Shellcheck"

install.sh
moved all zenity questions to one checklist.
needs lots of testing.
=> Redo Expert Mode

install.sh
Bumps PowerTools version again
https://github.com/NGnius/PowerTools/releases/tag/v0.5.0
https://github.com/NGnius/PowerTools/compare/v0.4.1...v0.5.0
=> PowerTools v0.5.0

configs/emulationstation/gamelists/n3ds/gamelist.xml, configs/emulationstation/gamelists/nds/gamelist.xml, configs/emulationstation/gamelists/ps2/gamelist.xml, install.sh
fixes problem with live files.
=> Gamelist hotfix

README.md, configs/emulationstation/gamelists/n3ds/gamelist.xml, configs/emulationstation/gamelists/nds/gamelist.xml, configs/emulationstation/gamelists/ps2/gamelist.xml, install.sh
=> Backport hotfix from main to dev

.gitpod.Dockerfile, .gitpod.yml, .gitpod/build/Dockerfile, README.md
look I know I scuffed the branch, I already had committed this change since then,
=> add gitpod

configs/mame/cfg/default.cfg
=> quick mame config change

functions/EmuScripts/emuDeckCemu.sh
Fixing the windows path issue described in #291
=> Fix #291 - Windows Path issue

configs/steam-rom-manager/userData/userConfigurations.json, functions/EmuScripts/emuDeckRetroArch.sh
Added parser for the Libretro SwanStation core.
=> Added SwanStation parser

EmuDeck_shell.ps1
Removing the use of cmdlet aliases to follow powershell best practices
=> Replaced cmdlet alias by full name

functions/ToolScripts/emuDeckSRM.sh
Attempts to resolve https://github.com/dragoonDorise/EmuDeck/issues/352. I can change the warning text if necessary, and could also try adding a checkbox with some kinda "don't ask again" prompt 🤷
=> Steam Rom Manager zenity prompt

tools/launchers/xenia.sh
Tried every version of Proton and Proton GE I could think of, installed various DK3D and DXGI / DXVK DLL replacements.
D3D12 renderer runs but output is shredded
Vulkan output still works on some games but not most.
Brought `xenia.sh` more in line with `cemu.sh`
=> Clean up xenia.sh

install.sh
Add URLs variables to simplify even more the commands part.
=> Split one liner for better readability

install.sh
Also add -o pipefail to catch actual failing command in bash pipeline.
=> Add trap to install.sh

configs/Ryujinx/Config.json
Fixes the controller id after the 1.1.383 update
Also updates the config to the newest version
Better test it locally before merging but it works for me
=> Update Ryujinx config

tools/launchers/yuzu.sh
Currently required to get bigger mods working. Yuzu already does this in its official flatpak distribution.
Untested since I have no steam deck - please make sure this does not cause permission error before merging.
=> Set higher file limit for yuzu

functions/EmuScripts/emuDeckRetroArch.sh
ROMs are already configured, just missing RA config setup
=> add pico8 and tic80 retroarch cores

tools/cloud/ChiakiRemotePlayClient.sh, tools/cloud/chiaki.sh
Better matching to SteamGridDB: https://www.steamgriddb.com/game/5319543
Currently matches to `Ochitsubaki`
=> Rename chiaki.sh to ChiakiRemotePlayClient.sh

configs/com.github.Rosalie241.RMG/config/RMG/mupen64plus.cfg
=> Added latest RMG configs + set dark theme

functions/cloudServicesManager.sh, tools/cloud/Amazon Luna (2020).sh, tools/cloud/Amazon Prime Video (2006).sh, tools/cloud/Apple TV.sh, tools/cloud/Crunchyroll.sh, tools/cloud/Discord.sh, tools/cloud/Disney+.sh, tools/cloud/Emby Theater (Program).sh, tools/cloud/HBO Max.sh, tools/cloud/Home Assistant (Program).sh, tools/cloud/Hulu.sh, tools/cloud/Jellyfin.sh, tools/cloud/Netflix.sh, tools/cloud/Paramount+.sh, tools/cloud/Peacock TV (2020).sh, tools/cloud/Plex.sh, tools/cloud/Spotify.sh, tools/cloud/TikTok.sh, tools/cloud/Twitch.sh, tools/cloud/Twitter.sh, tools/cloud/Vimeo (2004).sh, tools/cloud/Xbox Cloud Gaming (xCloud) (2019).sh, tools/cloud/YouTube Music (2015).sh, tools/cloud/YouTube TV.sh, tools/cloud/YouTube.sh, tools/cloud/cloud.conf, tools/cloud/webRcade.sh
Cloud Services Manager (CSM) Updates and bug fixes
- Added more supported browsers: Brave, Chromium
- Changed initially set browser to be the system default browser
- Added repair script with versioning for cloud.conf
=> CSM Updates and bug fixes

configs/steam-rom-manager/userData/userConfigurations.json, functions/EmuScripts/emuDeckRetroArch.sh, tools/chdconv/chddeck.sh
https://github.com/dragoonDorise/EmuDeck/issues/640
Bios, SRM, and CHD added. Retroarch core already installed.
=> Add SAME-Cdi

functions/ToolScripts/emuDeckESDE.sh
=> Actually Install ES-DE Steam Input Profile

tools/flatpakupdate/flatpakupdate.sh
Added ScummVM in flatpakupdate.sh
Fixed string comparison
=> flatpakupdate: Add ScummVM

tools/binupdate/binupdate.sh
binupdate emu selection fix
- Fixed emu *_IsInstalled comparison for update table
=> binupdate.sh Visible Emulators Fix

functions/updateEmuFP.sh, tools/flatpakupdate/flatpakupdate.sh
* Added emu selection and zenity progress in flatpakupdate for better user feedback on what's going on 
* Small change in updateEmuFP - verbose cp
=> flatpakupdate - user feedback

configs/org.libretro.RetroArch/config/retroarch/config/Beetle PCE Fast/pcengine.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Beetle PCE/pcengine.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Beetle PSX HW/psx.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Beetle PSX/psx.slangp, configs/org.libretro.RetroArch/config/retroarch/config/FinalBurn Neo/fbneo.slangp, configs/org.libretro.RetroArch/config/retroarch/config/FinalBurn Neo/neogeo.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Flycast/dreamcast.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Genesis Plus GX/genesis.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Genesis Plus GX/mastersystem.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Genesis Plus GX/megacd.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Genesis Plus GX/megadrive.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Genesis Plus GX/segacd.slangp, configs/org.libretro.RetroArch/config/retroarch/config/MAME 2003-Plus/mame.slangp, configs/org.libretro.RetroArch/config/retroarch/config/MAME/mame.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Mesen/nes.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Mupen64Plus-Next/n64.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Nestopia/nes.slangp, configs/org.libretro.RetroArch/config/retroarch/config/PUAE/amiga1200.slangp, configs/org.libretro.RetroArch/config/retroarch/config/PicoDrive/sega32x.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Snes9x/snes.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Snes9x/snesna.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Stella/atari2600.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Stella/atari800.slangp, configs/org.libretro.RetroArch/config/retroarch/config/YabaSanshiro/saturn.slangp, configs/org.libretro.RetroArch/config/retroarch/config/Yabause/saturn.slangp, configs/org.libretro.RetroArch/config/retroarch/config/bsnes-hd beta/snes.slangp
=> update CRT shader to crt-easymode

tools/launchers/yuzu.sh
- Remove dependency on google.
- Removed dependency on outbound port 53 being unblocked (many secure networks block this so DNS cannot be bypassed and have to resolve inside network)
- Test connection like it's about to be used (HTTPS connection to github)
=> Remove dependency on google

tools/binupdate/binupdate.sh
Added clearer names on logs for binupdate.sh
=> Updated naming on binupdate.sh

configs/steam-rom-manager/userData/parsers/emudeck/nintendo_gbc-ra-sameboy.json
no reason why there isn't one as there is one for the GB non color
=> Add Sameboy gbc parser

configs/mame/mame.ini, functions/EmuScripts/emuDeckMAME.sh
Closes https://github.com/dragoonDorise/EmuDeck/issues/756
Rebased as of june 9th
=> Hotfix MAME cheats and writing settings

configs/steam-rom-manager/userData/userConfigurations.json
=> SRM: update saturn parsers to include saturnjp

configs/steam-rom-manager/userData/parsers/emudeck/ares/atari_2600-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/bandai_wonderswan-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/bandai_wonderswan_color-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/benesse_pocket_challenge_v2-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/coleco_colecovision-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/microsoft_msx_1-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/microsoft_msx_2-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nec_pc_engine_supergrafx-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nec_pc_engine_turbografx_16-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nec_pc_engine_turbografx_16_cd-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nintendo_64-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nintendo_64dd-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nintendo_entertainment_system-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nintendo_famicom_disk_system-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nintendo_gameboy-advance-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nintendo_gameboy-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nintendo_gameboy-color-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/nintendo_snes-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/sega_32x-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/sega_cd_mega_cd-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/sega_game_gear-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/sega_genesis_mega_drive-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/sega_master_system-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/sega_sg_1000-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/sinclair_zx_spectrum-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/snk_neo_geo_pocket-ares.json, configs/steam-rom-manager/userData/parsers/emudeck/ares/snk_neo_geo_pocket_color-ares.json
Updated executable line to ares-emu.sh
=> Ares parsers hotfix

functions/ToolScripts/emuDeckSRM.sh, tools/srm/srm.sh
* Added srm.sh file
* Fixes launching SRM on GNOME Desktop Environments, should have no impact on SteamOS
=> Fix Steam ROM Manager Desktop File Not Launching on GNOME Desktop Environments

functions/ToolScripts/emuDeckCopyGames.sh
Instead of having one progress bar for everything, now it has one per folder so it's easier to see that it's actually working
=> Better USB Importer

functions/EmuScripts/emuDeckCitra.sh, functions/EmuScripts/emuDeckCitraLegacy.sh, functions/EmuScripts/emuDeckDolphin.sh, functions/EmuScripts/emuDeckDuckStation.sh, functions/EmuScripts/emuDeckMelonDS.sh, functions/EmuScripts/emuDeckPCSX2.sh, functions/EmuScripts/emuDeckPCSX2QT.sh, functions/EmuScripts/emuDeckPrimehack.sh, functions/EmuScripts/emuDeckRPCS3.sh, functions/EmuScripts/emuDeckRPCS3Legacy.sh, functions/EmuScripts/emuDeckRyujinx.sh, functions/EmuScripts/emuDeckVita3K.sh, functions/EmuScripts/emuDeckYuzu.sh, functions/ToolScripts/emuDeckSRM.sh, functions/autofix.sh, functions/helperFunctions.sh
Small fixes I noticed whilst using the latest version.
Details in commit descriptions.
=> Dev 2.2.1 Small Fixes

configs/Vita3K/config.yml, functions/EmuScripts/emuDeckPCSX2QT.sh
Vita3K config: default to Vulkan renderer
PCSX2 unfreeze
=> Dev Branch Emu Fixes

configs/org.citra_emu.citra/config/citra-emu/qt-config.ini, functions/EmuScripts/emuDeckCitra.sh
I was able to get an [Ocarina of Time 3D texture pack](https://www.youtube.com/watch?v=RNj5gZXZE7I&list=PLTnqFppEX3LV2e6wSQ5MrukcpJ_Nl-2aL&index=2) to load seemingly without issues, but I'm no citra expert 🤷 
- Symlinks citra texture folder on storage setup
- Enables citra custom textures, but not texture preloading bc it crashed for me even with a 1080p texture pack
- obligatory formatting
=> Citra custom textures

export.sh, functions/EmuScripts/emuDeckRetroArch.sh, functions/ToolScripts/emuDeckESDE.sh
Couple of small fixes from latest merges.
=> Dev Merge Fixes

functions/ToolScripts/emuDeckESDE.sh, functions/ToolScripts/emuDeckSRM.sh
ESDE - fix copying launcher on reset + formatting
SRM - string comparison + check if custom parsers folder exists beorehand
=> Dev ToolScript Fixes

configs/steam-rom-manager/userData/parsers/emudeck/sony_psp-ppsspp.json, configs/steam-rom-manager/userData/parsers/emudeck/sony_psp-ra-ppsspp.json
Added CHD support for PPSSPP
https://www.ppsspp.org/news/release-1.17/
=> Add CHD support for PPSSPP in Steam ROM Manager

functions/EmuScripts/emuDeckSupermodel.sh
=> Supermodel fixes

uninstall.sh
Back up BIOS and saves/states in uninstallation tool
=> Back up BIOS and saves/states in uninstallation tool

functions/EmuScripts/emuDeckRetroArch.sh
Buildbot downloader was stalling on unzip. Added a -q flag to all uses of unzip to see if this stops the stalling.
=> Use quiet flag with unzip in RA script

configs/steam-rom-manager/userData/parsers/emudeck/atari_jaguar-bigpemu_proton.json
* Hotfix BigPEMU Parser, bad slash
=> Hotfix BigPEMU Parser, bad slash

functions/EmuScripts/emuDeckModel2.sh, tools/launchers/model2.sh, uninstall.sh
* Switched ULWGL download to fetch from GitHub releases
* Froze ULWGL at 0.1-RC3 while waiting for ULWGL dev to stabilize
* Switched all wget downloads to curl downloads
* Switched to generic ULWGL Proton instead of a specific version
* Updated ULWGL paths to match latest ULWGL changes
* Updated uninstall and model2 files to match latest ULWGL changes
=> Model 2 ULWGL Updates

functions/EmuScripts/emuDeckBigPEmu.sh
* Switched back to curl to reduce dependencies
* Added permissions for bigpemu.sh in ~/Applications folder
* Swapped create BigPEmu folder to include UserData folder
=> Switch to curl in BigPEmu

functions/ToolScripts/emuDeckESDE.sh
New 3.0 update changes ES-DE config directory, updated to new ES-DE folder
=> [Hotfix ES-DE]

functions/ToolScripts/emuDeckESDE.sh
* Fixed names + used variables to reduce typos
* Added migrate function to install
=> EmulationStation-DE typo fixes

configs/emulationstation/custom_systems/es_systems.xml, functions/EmuScripts/emuDeckCemuProton.sh, functions/ToolScripts/emuDeckESDE.sh
* Added custom systems function for all emulators to ES-DE
* Moved Cemu Proton custom systems function to respective file
* Added path reset for Model 2 and BigPEmu
* Added all Proton emulators to es_systems.xml
=> ES-DE Proton Config Clean Up

functions/EmuScripts/emuDeckRMG.sh
* Fixed save/save state folders not being created
=> Hotfix RMG Save/Save State folders not being created

functions/ToolScripts/emuDeckESDE.sh
3.0 update changed settings path.
=> ES-DE: Update settings path

tools/chdconv/chddeck.sh
* Regression, will revert if fixed.
=> Compression tool: Remove CHD conversion for DC CUE/BIN ROMs

configs/cemu/config/cemu/controllerProfiles/Deck-Gamepad-Gyro.xml, configs/cemu/config/cemu/controllerProfiles/controller0.xml
* Accidentally removed, set to R3
=> Cemu: Add back mic hotkey

functions/ToolScripts/emuDeckESDE.sh, functions/ToolScripts/emuDeckSRM.sh, tools/binupdate/binupdate.sh
* Added Cemu to binupdate
* Added "$emuDeckEmuTypeAppImage" to ES-DE and SRM
* Alphabetized emulators in binupdate
=> binupdate: Fix cemu updating + alphabetized emulators

functions/EmuScripts/emuDeckPCSX2QT.sh, functions/EmuScripts/emuDeckYuzu.sh, functions/ToolScripts/emuDeckSRM.sh
* Added SRM_createParsers to PCSX2 and Yuzu
* Added a few missing RA cores to SRM_createParsers
=> Steam ROM Manager: Add missing RA parsers + tidy

tools/chdconv/chddeck.sh
* Fixed PSP hunksize
* Added GC, Wii, and PSP Decompression
=> Compression Tool: Add decompression options

functions/EmuScripts/emuDeckRyujinx.sh, tools/launchers/ryujinx.sh
* Launcher should point to .sh file to let Ryujinx adjust launch commands
=> Ryujinx: Hot fix saves + launcher

configs/model2/EMULATOR.INI, configs/steam-rom-manager/userData/userConfigurations.json, tools/launchers/model-2-emulator.sh
* Set WideScreenWindow to 1 (16:9) 
* Some graphical issues on 16:10
* Update launcher to disable/enable DrawCross based on game launched
=> Model 2: bbilford83 tweaks

functions/EmuScripts/emuDeckBigPEmu.sh, functions/EmuScripts/emuDeckCemu.sh, functions/EmuScripts/emuDeckCemuProton.sh, functions/EmuScripts/emuDeckModel2.sh, functions/EmuScripts/emuDeckRPCS3.sh, functions/EmuScripts/emuDeckXenia.sh, functions/ToolScripts/emuDeckESDE.sh
* Detect if ES-DE is installed before adding ES-DE custom config
* Set Ryujinx as priority
=> ES-DE: Tweaks

functions/appImageInit.sh
* If these folders already exists, it'll just make a subfolder instead
=> AppImageInit: Fix symlinking

configs/supermodel/Config/Supermodel.ini
* Fixed widescreen not applying properly
=> Supermodel: bbilford83 tweaks

functions/appImageInit.sh
* Automatically fixes the issue of launching into the emulator instead of the ROM
=> Reset launchers on EmuDeck launch

functions/appImageInit.sh
* Prevents forcefully applying the update
=> Launcher hotfix: Add zenity prompt and file flag

configs/emulationstation/custom_systems/es_systems.xml, functions/EmuScripts/emuDeckRPCS3.sh, functions/ToolScripts/emuDeckESDE.sh, tools/launchers/rpcs3.sh
* Fixed upstream, no longer needed
=> RPCS3: Remove ES-DE custom system

functions/ToolScripts/emuDeckPegasus.sh, roms/xbox360/xbla/metadata.txt, uninstall.sh
* Removed XBLA media folder 
* Steam ROM Manager parser picks up on all files
* Added desktop shortcut
=> Pegasus: XBLA and Desktop shortcut

functions/EmuScripts/emuDeckCitra.sh, functions/EmuScripts/emuDeckYuzu.sh, functions/ToolScripts/emuDeckESDE.sh, functions/appImageInit.sh, tools/chdconv/chddeck.sh
* Added back symlink migration
* Updated compression tool to use n3ds folder
* Fixed compression tool individual file picker for 3ds
=> Citra: Symlink migration, compression tool fixes

configs/cemu/config/cemu/settings.xml
* Fixes audio not working on certain devices
=> Cemu: Use default audio device

configs/steam-rom-manager/userData/userConfigurations.json
=> Steam ROM Manager: Revert xenia changes

setup.sh
* This was installing decky loader and emudecky without the user realizing
=> setup.sh: Remove EmuDecky install

functions/appImageInit.sh
=> appImageInit: More clean ups

configs/mame/cfg/default.cfg, configs/mame/mame.ini, configs/steam-input/emudeck_steam_deck_light_gun_controls.vdf, functions/EmuScripts/emuDeckFlycast.sh, functions/EmuScripts/emuDeckMAME.sh, functions/EmuScripts/emuDeckModel2.sh, functions/EmuScripts/emuDeckSupermodel.sh, uninstall.sh
* Added a Steam Input profile for light gun games since the default one is pretty horrendous
* Adjusted configurations for MAME so light gun games work OOTB with the Steam Input profile
=> Hotfix light gun games

configs/org.flycast.Flycast/config/flycast/mappings/SDL_Keyboard_arcade.cfg, configs/org.flycast.Flycast/config/flycast/mappings/SDL_controller_neptune_arcade.cfg
* Controls somehow got corrupted in the copy
=> Flycast: Hotfix controls

functions/EmuScripts/emuDeckCitra.sh, functions/EmuScripts/emuDeckRPCS3.sh, tools/launchers/citra.sh, tools/launchers/rpcs3.sh
* RPCS3: Remove double quotes
* Citra: Use flatpak name for detection
=> Citra/RPCS3: Fix Flatpak detection

functions/ToolScripts/emuDeckSRM.sh
=> Steam ROM Manager: Set Steam path

configs/emulationstation/custom_systems/es_systems.xml, functions/EmuScripts/emuDeckXenia.sh, functions/ToolScripts/emuDeckESDE.sh
* Added prefix injection into custom systems so users can add per-game configs
=> Xenia: Hotfix per game configs

tools/chdconv/chddeck.sh
Compression tool was not deleting the original files.
=> chddeck.sh: Hotfix 7z compression

functions/EmuScripts/emuDeckRetroArch.sh
Fixes https://github.com/dragoonDorise/EmuDeck/issues/1191
=> Issue #1191

functions/ToolScripts/emuDeckMigration.sh
Fixes https://github.com/dragoonDorise/EmuDeck/issues/1203
=> Issue #1203

functions/all.sh, functions/generateGameLists.sh
=> game list generator

functions/EmuScripts/emuDeckRetroArch.sh
* Less aggressive deleting in case the user creates these folders on their own
=> RetroArch: Hotfix texture pack folders Take 2

configs/emulationstation/custom_systems/es_systems.xml, configs/steam-rom-manager/userData/userConfigurations.json, functions/EmuScripts/emuDeckCemuProton.sh, roms/wiiu/roms/metadata.txt
* Added missing NUS file format
* Synchronized file formats across front-ends
=> Cemu: Hotfix/Synchronize File Formats

tools/cloud/Oqee by Free.sh
Hi,
I open this request to access OQEE by Free is a french cloud tv service, this website allow users to access public channel and subscribtions in france.
The app is fully compatible with the steam deck using the community controls
Thanks for having this quick config, your work is awesome !
=> Add OQEE by Free to Cloud Services

functions/EmuScripts/emuDeckRPCS3.sh
- use inbuilt function to find appropriate release from GitHub
=> Fix RPCS3 AppImage Download

functions/EmuScripts/emuDeckRPCS3.sh, functions/helperFunctions.sh, functions/installEmuAI.sh
- use the API to get latest release info without possible broken releases
- if the local file matches latest release checksum, it will not be redownloaded
- implement checkum checking in installEmuAI and safeDownload methods
- implement possibility of not downloading anything in installEmuAI (if local file exists)
=> RPCS3 Update API

functions/EmuScripts/emuDeckXenia.sh
- releases were moved to separate GH repo
- TODO: Linux build is available and working on SD, not sure about compatibility and if it is ready for production
┆Issue is synchronized with this [Trello card](https://trello.com/c/8k5J0OAL) by [Unito](https://www.unito.io)
=> Update Xenia Canary Release URL

functions/RemotePlayClientScripts/remotePlayChiaki.sh, functions/RemotePlayClientScripts/remotePlayChiaking.sh, functions/RemotePlayClientScripts/remotePlayGreenlight.sh, functions/RemotePlayClientScripts/remotePlayMoonlight.sh, functions/RemotePlayClientScripts/remotePlayParsec.sh, functions/RemotePlayClientScripts/remotePlayShadow.sh, functions/RemotePlayClientScripts/remotePlaySteamLink.sh
Shebang changes. Shellcheck stuff.
=> RemotePlay Cleanup

functions/GenericApplicationsScripts/genericApplicationBottles.sh, functions/GenericApplicationsScripts/genericApplicationCider.sh, functions/GenericApplicationsScripts/genericApplicationFlatseal.sh, functions/GenericApplicationsScripts/genericApplicationHeroic.sh, functions/GenericApplicationsScripts/genericApplicationLutris.sh, functions/GenericApplicationsScripts/genericApplicationPlexamp.sh, functions/GenericApplicationsScripts/genericApplicationSpotify.sh, functions/GenericApplicationsScripts/genericApplicationTidal.sh, functions/GenericApplicationsScripts/genericApplicationWarehouse.sh
More shebang changes and basic shellcheck stuff.
=> GenericApplications Cleanup

install-beta.sh, install-early.sh, install-unstable.sh, install.sh
For Gentoo support, tested and worked on myself machine.
=> Gentoo installation support
