dragoonDorise/EmuDeck

configs/Cxbx-Reloaded/cxbx-reloaded-wrapper
configs/Cxbx-Reloaded/settings.ini
configs/emulationstation/custom_systems/es_find_rules.xml
configs/emulationstation/custom_systems/es_systems.xml
configs/steam-rom-manager/userData/userConfigurations.json
install.sh

~~More feature complete, easier to set up and efficient than xemu.~~
A feature rich, efficient and easy to set up original xbox emulator:
- https://github.com/Cxbx-Reloaded/Cxbx-Reloaded
* A Bottle is set up (com.usebottles.bottles) to run it because Proton is erroring out when launching a game
* Automatically downloads the latest release if there is one
* Integrates into EmulationStation
* Steam Deck input binding functional
Note: Cxbx-Reloaded has an exclusive fullscreen option but it does bad things (resetting the desktop res and the rotation) on the deck and is not needed for fullscreen when launched in Game Mode.
Useful Hotkeys:
- ESC/Alt+F4: Close emulation
- F5: Start emulating
- F6: Stop emulating
- F9: Toggle framerate unlock hack
- F10/ALT+ENTER: Toggle fake windowed fullscreen …

[cxbx-reloaded] Add support for the original xbox emulator Cxbx-Reloaded

---

README.md
configs/steam-rom-manager/userData/userConfigurations.json

Dolphin has a neat little feature where you can create a JSON file for a given game mod that contains information about A) the "base game" and B) all modifications to be done to that game. That JSON file can be executed / loaded like a normal game file. 
This is very useful if you have a bunch of different game mods - you can just keep one base ISO and a bunch of JSON config files for your different mods, instead of having to waste space creating new full ISO files for your game mods. 
This PR adds "JSON" to the list of allowed file extensions for Wii games.
(Untested as I do not have my Steam Deck yet).

Add JSON as supported file extension for Wii games

---

configs/Cxbx-Reloaded/cxbx-reloaded-wrapper
configs/Cxbx-Reloaded/settings.ini
configs/emulationstation/custom_systems/es_find_rules.xml
configs/emulationstation/custom_systems/es_systems.xml
configs/steam-rom-manager/userData/userConfigurations.json
install.sh

A feature rich, efficient and easy to set up original xbox emulator:
- https://github.com/Cxbx-Reloaded/Cxbx-Reloaded
* A Bottle is set up (com.usebottles.bottles) to run it because Proton is erroring out when launching a game
* Automatically downloads the latest release if there is one
* Integrates into EmulationStation
* Steam Deck input binding functional
Note: Cxbx-Reloaded has an exclusive fullscreen option but it does bad things (resetting the desktop res and the rotation) on the deck and is not needed for fullscreen when launched in Game Mode.
Useful Hotkeys:
- ESC/Alt+F4: Close emulation
- F5: Start emulating
- F6: Stop emulating
- F9: Toggle framerate unlock hack
- F10/ALT+ENTER: Toggle fake windowed fullscreen
- F11: Switch between normal, wireframe, point graphics
*Jet Set …

[cxbx-reloaded] Add support for the original xbox emulator Cxbx-Reloaded v2

---

install.sh

Pulling directly from the main branch is dangerous, since it's not guaranteed to be stable.
This checks out v0.3.0 (latest release at time of PR) instead.

Checkout specific release tag from PowerTools

---

install.sh

Was not working before.
Was trying to copy from a place that didn't exist.
now copies to the tools folder on the selected install path, and points the desktopfile there.

installs chdtools to the tools folder.

---

install.sh
tools/chdconv/chddeck.sh

Now when the script and bin are dumped in the tools path, they get set as executable at that point.
The paths inside the script are updated according to what the user chose at the start of the emudeck install.
when the script is run it will scan the applicable folders only (many can't use chd) via whitelist variable.
it will search for gdi, bin, iso files.
the user will be presented with a list of folders with files which can be converted.
the user can select any set of these folders for processing.

rewrote chdman script

---

install.sh

added some of the flatpak overrides on as default because of a few complaintsin disc about the apps not opening / freezing when navigating accross filesystems.
make the launcher folder in tools
added a quick write out of the launcher files to the launcher directory during installation.

Fix installers

---

configs/emulationstation/custom_systems/es_systems.xml
install.sh
tools/launchers/cemu.sh

- Moved cemu.sh to launchers
- Adjusted install.sh and es_systems.xml to account for that
- Adjusted cemu.sh to handle not being in the same directory as Cemu.exe

Move cemu.sh to launchers, allow for Emulation tag in SRM

---

configs/net.pcsx2.PCSX2/config/PCSX2/inis/PCSX2_keys.ini
configs/steam-input/pcsx2_controller_config.vdf

There seems to be a bug in PCSX2 with mappings involving letter keys, like the current Shift-L and Shift-K.
I have changed the save/load state hotkeys to use Shift-F1 and Shift-F3 and also make use of the intended actions "States_FreezeCurrentSlot" and "States_DefrostCurrentSlot".
I also updated the steam input mapping for PCSX2 to make use of these new hotkeys. I was able to test this on my steamdeck.

Fix PCSX2 Save/Load state mappings

---

README.md

This change is to fix a typo on what type of Mupen64plus because the FZ variant of mupen64plus is a android edition of the program which this isn’t installing. Don’t want to add any confusion if people take it literally. Especially since there is many variants of Mupen64plus like for example Mupen64plus-ae or mupen64plus-core. I redid PR because I didn’t follow dev guideline in readme and have no conflicts like previous.

Readme Fix: name change mupen64plus FZ

---

install.sh

This PowerTools update fixes the display breakage from the latest SteamOS update
https://github.com/NGnius/PowerTools/releases/tag/v0.4.1

Update PowerTools to v0.4.1

---

configs/steam-rom-manager/userData/userConfigurations.json

This PR adds the .bin extension for Sega Genesis, and also adds a parser for Commodore 64.

Fix Sega Genesis missing extension and adds Commodore 64

---

install.sh

This PR adds a few tests for non-valve devices running holoISO that correct missing dependencies so the emudeck installation completes successfully.
1. Verify that we're not executing on a Steam Deck.
2. Ensure dependent softwares are installed.
3. Make sure flatpak can install to the system without root.
4. Ensure that the Desktop directory is not owned by root.

Add support for holoISO

---

configs/steam-input/citra_controller_config.vdf

In Citra the right trackpad click action was set to Right Stick Click, and I thought Left Mouse Click would feel more natural for the trackpad. Found the new binding `mouse_button LEFT` by exporting my edited config and checking the diff.

Adds citra touchpad clicking

---

configs/steam-input/citra_controller_config.vdf

Changes Citra mapping for the Left Trackpad from a D-pad to a mouse/click combo, similar to https://github.com/dragoonDorise/EmuDeck/pull/209. Figured this solves using the touchscreen + the A/B/X/Y buttons simultaneously + is just more useful than a touch D-pad next to the physical D-pad 🤷

Citra left trackpad as mouse instead of D-pad

---

configs/steam-rom-manager/userData/userConfigurations.json

- Add nkit.gcz format to Nintendo Wii - Dolphin in Steam Rom Manager

Add nkit.gcz format to Nintendo Wii - Dolphin

---

README.md
configs/net.pcsx2.PCSX2/config/PCSX2/inis/PCSX2_keys.ini
configs/steam-input/pcsx2_controller_config.vdf

- Resolves PCSX2 TurboMode (FFWD/Fast Forward) Keybinds as shift+m wasn't functioning
- Utilizes R4 (by default was S) as S was not used in PCSX2
- Update README to correctly reflect this change

Fix Turbo Mode for PCSX2

---

README.md

This pull request is about adding xemu (Xbox emulator) to the main readme of the GitHub repo. I wasn’t sure to add Sega chihiro since xemu has not fully implemented features for them to work either.

Adds Xemu to README.md

---

configs/steam-rom-manager/userData/userConfigurations.json

Previously was missing the period in the extensions and was only looking for lower case.

WiiU steam-rom-manager glob update

---

tools/chdconv/chddeck.sh

deleted dolphintool.exe in favor of dolphin-tool in the flatpak binary dir.
Fixes: #216
Fixes: #103

CHDDeck now finds and removes files from gdi and cue

---

.github/workflows/CI.yml

Unsure if this is something this project wants, but I finally got some time to work on this and threw together some GitHub Actions CI jobs real quick.
Adds GHA lint jobs for:
- `.sh` with shellcheck & shfmt
- `.md` with markdownlint
- `.ps1` with PSScriptAnalyzer
I've got a [summary of a demo run here](https://github.com/DylanTackoor/EmuDeck/actions/runs/2480499236). Assuming some CI jobs like this are wanted, I could start fixing the shellscript lint errors and provide hosting for the GHA runners.
I'd also need to check if the powershell linting is actually working as I've only touched ps scripts once before 🙃

Adds GitHub Actions linting

---

functions/EmuScripts/emuDeckRetroArch.sh

As discussed in #294:
> With a rumble pak, saving games is not possible. IMO, the default configuration should at least allow people to have saves.
This was introduced in https://github.com/dragoonDorise/EmuDeck/commit/6faa114051d204ee92fd26887bdac5620d46a45e.
> I would rather have saving work out of the box without having to use save states than rumble. This is, however, personal preference.
I also believe having to use save states is rather unintuitive for new and non-tech-savvy users, who might not know about them or the needed keybinds. For these users, having the memory pak enabled would most likely improve the out-of-the-box experience.

Mupen64Plus-Next: Changed default controller pak back to "memory"

---

configs/steam-input/citra_controller_config.vdf

Labels the grip buttons in the Citra config 😄

adds labels to citra's grip button mappings

---

configs/steam-rom-manager/userData/userConfigurations.json

While both `genesis` and `megadrive` ROM directories are created when installing EmuDeck, only the `genesis` directory has an associated parser in Steam ROM Manager.
As a European, I used the `megadrive` directory as it's the name that comes to mind when I think of the console. So I was caught out when Steam ROM Manager didn't generate any entries for those Mega Drive games. This change fixes that issue.
The configuration here was copied from Steam ROM Manager on my Deck after copying the Genesis parser then modifying and saving the copy. (Then fixing the indentation.)

Set up dual region Steam ROM Manager parsers

---

tools/proton-launch.sh

Moved the shift of the options out of the arguments to make more sense
Added `showArguments` to output all arguments to help with troubleshooting
Added an integer check for the `-i` option.

proton-launch.sh - Catch some common argument errors

---

tools/appID.py

Using sys.exit will actually exit from the python interpreter, while exit may require user interaction.
Also save a little time as there's no need for an else statement.

[appID.py] Exit immediately if arguments are not 3

---

tools/launchers/cemu.sh
tools/launchers/xenia.sh
tools/proton-launch.sh

Add -
$steamPaths - Use the libraryfolders.vdf to find all Steam install paths
installProton - Called by findProton if Proton version isn't installed. Checks known list and attempts to have Steam install Proton.
findProton - Looks for Proton version specified in every available Steam path
Other Changes -
Rearranged more of the code for readability
Possible further changes in the future -
Consider if maybe setting most of the options / arguments as environment variables might be better.

Find all steam paths. Catch uninstalled Proton and attempt to install

---

configs/steam-rom-manager/userData/userConfigurations.json

Fix ryujinx's steam category to be in the same format as yuzu's

---

functions/EmuScripts/emuDeckCitra.sh

Quick symlink based on Ryujinx script to add the folder needed to store AES keys into the bios folder

add sysdata symlink to bios folder for citra

---

tools/remoteplaywhatever/remoteplaywhatever.sh
tools/updater/emudeck-updater.sh

The /bin/sh file is a link, not an actual binary, and that can point to /bin/bash as well as other shells, like /bin/dash in recent ubuntu versions.
To be consistent between linux distributions, and avoid issues like missing support for bash functions (e.g. source), let's call /bin/bash instead.

Explicitely call bash instead of /bin/sh

---

tools/proton-launch.sh

`compatibilitytools.d` misspelled as `compatabilitytools.d`, breaking Proton-GE use in holiday update.

Bug Fix - Fix compatibilitytools.d spelling error

---

configs/steam-rom-manager/userData/userConfigurations.json

Adds a predefined configuration for EasyRPG to the Steam Rom Manager.
Games must be placed in the `easyrpg` folder in the directory of the other roms. In an RPG Maker game, the executable is always called the same. Therefore, the folder name must be used as the title. The `title` and not the `fuzzyTitle` must also be used for the image query.

Steam Rom Manager configuration for EasyRPG

---

functions/EmuScripts/emuDeckRetroArch.sh

The directory is `DOSBox-pure` and not `DOSBox Pure`
Fixes https://github.com/dragoonDorise/EmuDeck/issues/534

Fix DOSBox-pure config directory

---

functions/ToolScripts/emuDeckPlugins.sh

Decky's installer has moved so you'll need to point at the new location
To be clear, this isn't urgent so no rush

Use new decky installer location

---

functions/updateEmuFP.sh

Fixed flatpak launcher scripts update path (missing slash) - No such file or directory errors in log
On every flatpak update (tools & stuff, update emulators, update flatpaks) there are bunch of errors in the log and the launcher scripts are not updated. This should fix that.
```
[Sun Jan 15 02:25:04 AM CET 2023] stderr: find: ‘/run/media/mmcblk0p1/Emulation/toolslaunchers/’: No such file or directory
cp: cannot create regular file '/run/media/mmcblk0p1/Emulation/toolslaunchers/primehack.sh': No such file or directory
chmod: cannot access '/run/media/mmcblk0p1/Emulation/toolslaunchers/primehack.sh': No such file or directory
find: ‘/run/media/mmcblk0p1/Emulation/toolslaunchers/’: No such file or directory
cp: cannot create regular file …
```

Fixed flatpak launchers update

---

configs/steam-rom-manager/userData/userConfigurations.json

* PS2 Parser: `PlayStation 2` to `PlayStation 2`
* PC98 Parser: Updated ROM Directory and Libretro Core
* Wii Parser: Added `.json` and `.JSON` file types

PS2 Parser, PC98 Parser, Wii Parser Changes

---

functions/RemotePlayClientScripts/remotePlayChiaki.sh
functions/RemotePlayClientScripts/remotePlayMoonlight.sh
functions/RemotePlayClientScripts/remotePlayParsec.sh
functions/all.sh
functions/cloudServicesManager.sh
tools/remoteplayclients/Parsec.sh

Fixed Parsec & Remote Play Launchers
- Fixed Parsec crashing when opening from Steam
- Added update/repair of remote play client launchers
- Added `CloudScripts_update` function to cloudServicesManager.sh for externally updating scripts
- Fixed typos

Fixed Parsec & Remote Play Launchers

---

system-setup.sh

Created a new script for setting up some of the prerequisite packages needed to install EmuDeck. At the moment, this only supports Debian and Arch but anyone is free to add in their own preferred distros.

feat: Create setup script for linux desktop

---

configs/steam-rom-manager/userData/userConfigurations.json

For DSIware emulation
Requires external DSI BIOS and switching the `Console Type` to `DSI` in MelonDS.

SRM - Add "app" file type to Standalone MelonDS

---

store/gba/Apotris.json

this PR adds the needed json for accessing Apotris.
Works hand-in-hand with https://github.com/EmuDeck/emudeck-homebrew/pull/1

add json for apotris.

---

functions/helperFunctions.sh
tools/savesync.sh

Added "contains" argument, allows for more granular filtering of GitHub releases
No changes if no argument or empty argument is supplied
Removed duplicated getReleasURLGH() from savesync.sh (it sources all.sh)
Notes: 
- I am playing with Ryujinx Avalonia builds and although the changes above do not appear used yet, it comes in handy at least for that (getting -ava builds).
- The helperFunctions.sh file tabs/spaces indentation is a mess. I opted to use tabs for these changes but should probably be unified throughout whole file.

helperFunctions - getReleaseURLGH / getLatestReleaseURLGH

---

functions/RemotePlayClientScripts/remotePlayChiaki.sh
functions/RemotePlayClientScripts/remotePlayMoonlight.sh
functions/RemotePlayClientScripts/remotePlayParsec.sh

Fixes issue #713 "Parsec Gaming Mode shortcut not launching with new EmuDeck Update"
- Ensures that the remote play clients are installed to the "user" level and not the "system" level
- You need to launch "Cloud Services Manager" then go to the "Remote Play Clients" menu. Upon entering the menu, the fix will be applied if necessary.

Added a check to Remote Play Clients

---

configs/steam-input/ares_controller_config.vdf
configs/steam-input/cemu_controller_config.vdf
configs/steam-input/citra_controller_config.vdf
configs/steam-input/emulationstation-de_controller_config.vdf
configs/steam-input/mGBA_controller_config.vdf
configs/steam-input/melonds_controller_config.vdf
configs/steam-input/ppsspp_controller_config.vdf
configs/steam-input/rmg_controller_config.vdf

* Adds a sort of "readme" icon to the ES-DE profile as the center icon with instructions on how to use the profile
* Changes main menu of ES-DE profile to a radial menu
* Accidentally flipped the text for reset/stop emulation on the ares profile
* Adds Gyro to Cemu, Citra, and ES-DE
* Adds (Standalone) to ES-DE icons when applicable
* Adds (Standalone) to mGBA and melonDS profiles
* Adds full screen hotkey for Cemu (Long press L5/R5)
* Use a more consistent naming convention for full screen - "Toggle Full Screen"
* Adjust pressing timings from 1 second to .3 seconds of the ESDE Emulator profiles

Steam Input Profile Updates

---

functions/ToolScripts/emuDeckMigration.sh

This should make it so that when a user uses the migration tool, they don't have to reset the config for SRM after.

Hotfix: adds updating the roms path in usersettings to the migration

---

configs/steam-rom-manager/userData/parsers/emudeck/nintendo_gc-dolphin.json
configs/steam-rom-manager/userData/parsers/emudeck/nintendo_wii-dolphin.json
configs/steam-rom-manager/userData/parsers/emudeck/sega_dreamcast-Flycast.json
tools/launchers/flycast.sh

* Fixed Flycast executable line (was causing errors)
* Removed M3U from Flycast parser (standalone does not support M3U apparently)
* Updated Flycast launcher script to add cloud support
* Removed redundant "launch Dolphin" line from Dolphin parsers

Hotfix Dolphin and Flycast Parsers

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml

* Add template issues to GitHub.
* Adds a bug report and feedback template. 
* Adds links to Discord and the EmuDeck Wiki.

GitHub Issue Templates

---

uninstall.sh

Remove cemu and xenia related files in respective ROM folders, keep the secondary ROM folder itself.

Update cemu and xenia uninstall methods

---

system-setup.sh

This is to add support for those who want to run EmuDeck on Fedora-based systems like Nobara or regular Fedora.

Add Fedora option to `system-setup`

---

configs/net.rpcs3.RPCS3/config/rpcs3/config.yml

Testing a few config options to hopefully improve performance with RPCS3 on the deck.
All of this needs extensive testing besides probably Vsync and FSR enabled (won't do anything currently).
- Use FSR for output scaling
- Ideally downscale resolution to match to 75% or 50% to reduce load on CPU as a benefit
- Multithreaded RSX
- Vsync On
- SPU Blocksize Mega
Possible further optimizations:
- ZCULL Accuracy -> Approx/Relaxed
- Shader Mode -> Async with Shader Interpreter
- SPU Blocksize -> Giga
- Shader Quality -> Auto
- CPU XFloat Accuracy -> Relaxed
- Resolution Scale -> 50%/75%
Reference: https://wiki.rpcs3.net/index.php?title=Help:Default_Settings

RPCS3 FSR and optimizations

---

functions/EmuScripts/emuDeckRPCS3.sh
tools/binupdate/binupdate.sh
uninstall.sh

Continuing discussion from https://github.com/dragoonDorise/EmuDeck/pull/784#issuecomment-1701575741  
Makes sense to me to do this. 
I'm not sure how migration will be exposed in the UI though since the last migration with Yuzu was still using the cli version of EmuDeck. Or is adding the migration function to these two sections enough on its own?
@SilentException @dragoonDorise
Thank you SilentException!

Update RPCS3 migration

---

tools/cloud/Nebula.sh

This PR should add [Nebula](https://nebula.tv/) as a Cloud Service. 
However, I'm not sure if this works, as there isn't much documentation (that I could find) on how to add new cloud services.
Additionally, [this](https://github.com/dragoonDorise/EmuDeck/wiki/cloud-services) wiki page would need to be updated, but I'm unsure how to do that with a PR.
Apologies for not using the dev branch to make this PR, but it hasn't yet been updated to have cloud service support, so I couldn't work with it. 
Since I haven't tested this to see if it works, I'm open to adding any additional code that might be necessary to make it functional. Currently, this serves more as a suggestion than a final PR.

Added Nebula as a Cloud Service

---

functions/EmuScripts/emuDeckCemuNative.sh
functions/EmuScripts/emuDeckMGBA.sh
functions/EmuScripts/emuDeckPCSX2QT.sh
functions/EmuScripts/emuDeckRyujinx.sh
functions/EmuScripts/emuDeckVita3K.sh
functions/EmuScripts/emuDeckYuzu.sh
functions/installEmuAI.sh
functions/installEmuBI.sh
uninstall.sh

* altName -> fileName
* fileName is used for the AppImage file name only, use the "real" name for the shortcut
* adapt emu scripts - only PCSX2 makes use of this
* small changes in other scripts to use emuName variable instead of hardcoded strings

InstallEmuAI/InstallEmuBI Tweaks

---

functions/EmuScripts/emuDeckCitra.sh

See earlier PRs

---

functions/helperFunctions.sh

The previous way of checking whether a package was installed or not was incorrect in its assumption, that a package ID will only occur once in the flatpak installed list.
I noticed this while trying to install PPSSPP, as FlatPak installs a `org.ppsspp.PPSSPP` and `org.ppsspp.PPSSPP.Locale` package. The package was installed correctly, but EmuDeck would register it as non-installed.

helpers: Fix FlatPak installed check

---

functions/EmuScripts/emuDeckVita3K.sh

o/, this is my first PR here, im not sure if this is exactly the right thing to do but anyways, Vita3K changed where the config.yml file is located, now respecting XDG spec, defaulting to `~/.config/Vita3K/config.yml` if `XDG_CONFIG_HOME` is not set, also idk if its handled automatically the case where the Vita3K folder doesnt exist in .config, just a heads up. btw i was told to PR this to main branch as its a hotfix

Update Vita3K's default config path

---

functions/EmuScripts/emuDeckVita3K.sh

* With the new config path, current EmuScript doesn't properly initialize configurations. Updated path to new config location.

[Hotfix] Vita3K

---

import.sh

@dragoonDorise 
Added the `L` flag for saves to allow copying symlink'd saves (RA, Citra, Dolphin)

[Hotfix] import.sh

---

tools/proton-launch.sh

* Remove the arguments section to allow launching emulators with flags
Fixes https://github.com/dragoonDorise/EmuDeck/issues/960

Hotfix proton-launch.sh

---

functions/ToolScripts/emuDeckPlugins.sh

- Updates the DeckyControls plugin installation to pull from [EmuDeck/EmuDecky](https://github.com/EmuDeck/EmuDecky) rather than the deprecated [EmuDeck/emudeck-decky-controls](https://github.com/EmuDeck/emudeck-decky-controls) repo.
- Cleans up lingering emudeck-decky-controls installations.
- Fixes broken `chown` and `chmod` calls that referenced the old installation directory.
I believe this closes #925.

Update EmuDecky Installation

---

tools/launchers/model2.sh

* Added zenity progress bar for downloading protonfixes 
* Protonfixes may take approximately a minute to download, using this duct tape solution to show the user something

Add zenity progress bar to model 2 launcher

---

functions/EmuScripts/emuDeckModel2.sh

* Adjusted ES-DE to use arcade platform instead of model 2 for better scraping 
* Matches ES-DE defaults

Adjust Model 2 config to use arcade platform in ES-DE

---

configs/cemu/config/cemu/settings.xml
functions/EmuScripts/emuDeckCemu.sh

* Fixed menu bar appearing in fullscreen
* Fixed Cemu not applying configs properly
Not 100% sure why the `declare -A` was removed but that seems to be breaking Cemu not actually applying any of its configs. Added it back.

Cemu Bug Fixes

---

functions/cloudServicesManager.sh

I didn't test this but it looks like this was reverted in everything except Cemu and this file. I have another PR for Cemu so may as well revert it here.

Revert declare -a removal in cloudServicesManager

---

configs/steam-rom-manager/userData/parsers/emudeck/atari_jaguar-bigpemu_proton.json

* BigPEmu Parser 
* Removed fallback icon 
* Fixed executable field not populating 
* Updated parser to latest format (Through Steam ROM Manager)

Steam ROM Manager: BigPEmu Parser

---

configs/supermodel/Config/Supermodel.ini

* Removed rawinput, not working on Steam Deck
* Set input driver to SDL
* Updated mouse inputs so right trackpad on Steam Deck works ootb 
* I don't have light guns so I am not sure if the mouse2 inputs need to be updated to mouse1 or not
* Added R3 as an alternative input for the "A" button in lightgun games so "Gamepad with Mouse Trackpad" works OOTB
* Set resolution to 1280x800p so right trackpad can reach the entire screen

Supermodel Controls

---

functions/ToolScripts/emuDeckESDE.sh

* If migration is not done first, .emulationstation directory is moved inside of the newly created ESDE folder, moved migration to ToolScripts

EmulationStation-DE Hotfix

---

functions/ToolScripts/emuDeckESDE.sh

* If migration is not done first, .emulationstation directory is moved inside of the newly created ESDE folder, moved migration to ToolScripts

ES-DE Hotfix Early

---

configs/org.duckstation.DuckStation/config/duckstation/settings.ini

* Removed duplicate hotkeys - PGXP and Software Rendering 
* Duplicates were still in conflict with other hotkeys (quick menu and the new software rendering hotkey)

DuckStation Hotkeys Hotfix 

---

functions/EmuScripts/emuDeckBigPEmu.sh
functions/EmuScripts/emuDeckCemuProton.sh
functions/EmuScripts/emuDeckModel2.sh
functions/EmuScripts/emuDeckXenia.sh
uninstall.sh

* Fixed uninstall methods for BigPEmu, Cemu Proton, Model 2, and Xenia 
* The individual uninstall button in the EmuDeck application will wipe everything except the ROMs and saves folder
* The global uninstall script will save BIOS and saves on request but will wipe everything else otherwise
* Fixed Xenia save paths (so the uninstall bit works properly)

Tidy up Proton Uninstall Functions

---

configs/emulationstation/custom_systems/es_systems.xml
functions/ToolScripts/emuDeckESDE.sh

* Swapped Cemu Proton and Native for the custom systems file
* Added detection for a junk settings file where if a user updated without the settings fix, they would get this junk file instead
* Set melonDSDS as the default
* Use %BASENAME% instead of %ROM% for Model 2

ES-DE: melonDSDS default, Model 2 custom system, more fixes

---

configs/steam-rom-manager/userData/parsers/emudeck/arcade_atomiswave-flycast.json
configs/steam-rom-manager/userData/parsers/emudeck/arcade_naomi-flycast.json
configs/steam-rom-manager/userData/parsers/emudeck/arcade_naomi-ra-flycast.json
configs/steam-rom-manager/userData/parsers/emudeck/arcade_naomi2-flycast.json
configs/steam-rom-manager/userData/parsers/emudeck/sony_ps3-rpcs3-extracted_iso_psn.json
configs/steam-rom-manager/userData/parsers/emudeck/sony_ps3-rpcs3-pkg.json

* Fixed RPCS3 ROMs not being escaped properly
* Fixed extra quote in Flycast parser
* Fixed file formats in Flycast arcade parsers
* Fixed fuzzy matching in Flycast arcade parsers

Steam ROM Manager: Fix RPCS3 and Flycast parsers

---

configs/emulationstation/custom_systems/es_systems.xml
functions/EmuScripts/emuDeckModel2.sh
functions/ToolScripts/emuDeckESDE.sh
tools/launchers/model-2-emulator.sh

* The old name was triggering mismatches on SteamGridDB

Model 2 Emulator: Rename launcher

---

configs/emulationstation/custom_systems/es_systems.xml
functions/EmuScripts/emuDeckXenia.sh
functions/ToolScripts/emuDeckPegasus.sh

* A broken media symlink for Pegasus was causing ES-DE to detect it as a ROM. 
* Now creates this folder on reset.
* The LICENSE file was causing ES-DE to detect it as a ROM. 
* Renamed LICENSE to LICENSE.TEXT
* .git was being detected as a ROM. 
* Removed this and replaced how xenia grabs patches.
Closes: https://github.com/dragoonDorise/EmuDeck/issues/1078

Xenia: Fix ES-DE detection + clean up custom systems

---

uninstall.sh

Since Pegasus was swapped over to the binary, it uses new config folders.

Uninstall: Fix pegasus uninstall

---

configs/pegasus-frontend/game_dirs.txt
functions/ToolScripts/emuDeckPegasus.sh
roms/arcade/metadata.txt
roms/atarijaguar/metadata.txt
roms/atarijaguarcd/metadata.txt
roms/gc/metadata.txt
roms/model2/metadata.txt
roms/model2/roms/metadata.txt
roms/model3/metadata.txt
roms/n64dd/metadata.txt
roms/nds/metadata.txt
roms/ps3/metadata.txt
roms/psp/metadata.txt
roms/switch/metadata.txt
roms/vsmile/metadata.txt
roms/wii/metadata.txt
roms/wiiu/roms/metadata.txt
roms/xbox360/roms/metadata.txt
roms/xbox360/xbla/metadata.txt
tools/launchers/rpcs3.sh

* Fixed Model 2 Emulator and Supermodel metadata files
* Moved metadata files and metadata to rom subfolder for Proton emulators
* Added RPCS3 support through desktop files
* Adjusted defaults 
* Atari Jaguar/Atari Jaguar CD changed to BigPEmu 
* Arcade changed to MAME (standalone) 
* NDS changed to melonDS DS 
* Nintendo 64DD changed to RMG 
* PSP changed to PPSSPP (Standalone) 
* Nintendo Switch changed to Ryujinx (Standalone) 
* VSmile changed to MAME (Standalone)
* Removed z: from wiiu metadata file since it's presumably running Cemu Native

Pegasus: Tweaks and Fixes

---

configs/rpcs3/GuiConfigs/CurrentSettings.ini
configs/rpcs3/config.yml
configs/steam-rom-manager/userData/parsers/emudeck/sony_ps3-rpcs3-pkg.json
configs/steam-rom-manager/userData/userConfigurations.json

* Steam ROM Manager: Hotfix RPCS3 Parser
* Corrected custom variable, fixes installed PKGs not parsing
* Set fullscreen mode to false, seems to be broken at the moment on OLED Steam Decks
* Set Full Width AVX-512 to true, should be on by default (RPCS3 will automatically detect if it can use this setting or not)
* Set gamepad configs to true

RPCS3: Tweaks and Fixes

---

configs/steam-rom-manager/userData/userConfigurations.json
functions/ToolScripts/emuDeckSRM.sh

* Added a line to fetch latest custom variables file
* Steam ROM Manager recently updated to use PSN instead of PS3 for RPCS3, adding this line allows EmuDeck to grab the latest changes
* Fixed fuzzy matching on Supermodel by adding MAME variable

Steam ROM Manager: Custom Variables + Supermodel Parser 

---

functions/ToolScripts/emuDeckSRM.sh
functions/appImageInit.sh

* Used to reset Steam ROM Manager, PCSX2, DuckStation, and Citra on launch (if users had the old SRM AppImage)

appImageInit: Fix SRM migration

---

functions/checkBIOS.sh

* BIOS Checker now checks for the presence of both Ryujinx keys and firmware instead of checking for Yuzu keys
* If both keys and firmware are not in place (if one is missing), checker will fail
Wasn't sure if I should update the function name since that's what the app is looking for.

checkBIOS: Detect Ryujinx instead of Yuzu

---

configs/steam-input/emudeck_controller_generic.vdf
configs/steam-input/emudeck_controller_ps4.vdf
configs/steam-input/emudeck_controller_ps5.vdf
configs/steam-input/emudeck_controller_ps5_dualsense_edge.vdf
configs/steam-input/emudeck_controller_steamdeck.vdf
configs/steam-input/emudeck_controller_steamdeck_radial_menus.vdf
configs/steam-input/emudeck_controller_switch_pro.vdf
configs/steam-input/emudeck_controller_xbox360.vdf
configs/steam-input/emudeck_controller_xboxone.vdf
configs/steam-input/emudeck_frontend_controller_generic.vdf
configs/steam-input/emudeck_frontend_controller_ps4.vdf
configs/steam-input/emudeck_frontend_controller_ps5.vdf
configs/steam-input/emudeck_frontend_controller_ps5_dualsense_edge.vdf
configs/steam-input/emudeck_frontend_controller_steamdeck.vdf
configs/steam-input/emudeck_frontend_controller_switch_pro.vdf
configs/steam-input/emudeck_frontend_controller_xbox360.vdf
configs/steam-input/emudeck_frontend_controller_xboxone.vdf

* Set deadzone to default (was accidentally turned off previously)
* Set L4/R4 and L5/R5 to blank on the all profile 
* Seems to be a Steam Input bug so set these to be cleared from parent to prevent any misinputs
* Fixed PCSX2 quick menu hotkey in the radial profile

Steam Input Profile Tweaks

---

configs/org.flycast.Flycast/config/flycast/mappings/SDL_controller_neptune.cfg
configs/org.flycast.Flycast/config/flycast/mappings/SDL_controller_neptune_arcade.cfg

* Removed select as quick menu for arcade games (still works on Dreamcast games)
* Set coin to select for arcade games
* Added default mapping for dreamcast games 
* controller_neptune is what the Steam Deck uses for Flycast even though the emulator seems to expose various other similar sounding options

Flycast: Hotfix arcade controls + add default mapping

---

configs/steam-input/emudeck_controller_generic.vdf
configs/steam-input/emudeck_controller_ps4.vdf
configs/steam-input/emudeck_controller_ps5.vdf
configs/steam-input/emudeck_controller_ps5_dualsense_edge.vdf
configs/steam-input/emudeck_controller_steamdeck.vdf
configs/steam-input/emudeck_controller_switch_pro.vdf
configs/steam-input/emudeck_controller_xbox360.vdf
configs/steam-input/emudeck_controller_xboxone.vdf
configs/steam-input/emudeck_frontend_controller_generic.vdf
configs/steam-input/emudeck_frontend_controller_ps4.vdf
configs/steam-input/emudeck_frontend_controller_ps5.vdf
configs/steam-input/emudeck_frontend_controller_ps5_dualsense_edge.vdf
configs/steam-input/emudeck_frontend_controller_steamdeck.vdf
configs/steam-input/emudeck_frontend_controller_switch_pro.vdf
configs/steam-input/emudeck_frontend_controller_xbox360.vdf
configs/steam-input/emudeck_frontend_controller_xboxone.vdf

* Removed F11 from R4/L4, these were used for both toggle screen layout and toggle full screen which conflict with each other (if you toggle your screen, you end up toggling full screen at the same time).
* Added Toggle Screen Layout to Select + Y
* Added Swap Screens to Select + X
* Cleaned up hotkey wording

Hotfix Steam Input Profiles

---

configs/org.flycast.Flycast/config/flycast/emu.cfg
configs/org.flycast.Flycast/config/flycast/mappings/SDL_Keyboard_arcade.cfg
functions/EmuScripts/emuDeckFlycast.sh

* Set service key to L3
* Set test key to R3
* Moved insert card key to enter (STEAM + DPad Right)
* Added directories for Atomiswave, NAOMI, and NAOMI 2 to Flycast
* Fixed fullscreen scaling bug (fixes Flycast GUI in game mode)

Flycast: Hotfixes

---

functions/EmuScripts/emuDeckCitra.sh
functions/EmuScripts/emuDeckDolphin.sh

* Added detection for both AppImage and Flatpak
* Copied saves from Flatpak to AppImage if both are detected
* Resized zenity prompt

Citra: Fix init detection + copy saves

---

functions/ToolScripts/emuDeckPegasus.sh

Added an --ignore-existing so it only adds the folders if they've been deleted. This was previously breaking the Citra and Dolphin symlink cleanup.

Pegasus: Fix rsyncing ROMs folder

---

tools/chdconv/chddeck.sh

* Not using ZSTD can cause issues since EmuDeck is using a higher hunk size

chddeck: Use ZSTD for createdvd compression

---

configs/pegasus-frontend/game_dirs.txt
functions/ToolScripts/emuDeckESDE.sh
functions/ToolScripts/emuDeckPegasus.sh
functions/ToolScripts/emuDeckSRM.sh

* Added detection to delete mame2003 and mamecurrent symlinks
* Removed mame2003, mame2010, and mamecurrent from Pegasus configs
* Changed the mame folder to use MAME current through Pegasus

RetroArch MAME cleanups

---

functions/ToolScripts/emuDeckSRM.sh

* Users were experiencing freezing/crashing with Steam ROM Manager on the new EmuDeck update. This wipe cache function "resets" the non-Steam library and ideally should fix any crashing or freezing.
Requires a "Delete Cache" button to be added to the below page and hooked up to `SRM_deleteCache`

Steam ROM Manager: Add delete cache function

---

configs/org.citra_emu.citra/config/citra-emu/qt-config.ini
functions/EmuScripts/emuDeckCitra.sh

* Flatpak and AppImage configs were tangled. Added sed commands to redirect AppImage to AppImage paths.

Citra: Hotfix freezing

---

functions/EmuScripts/emuDeckBigPEmu.sh
functions/EmuScripts/emuDeckCemu.sh
functions/EmuScripts/emuDeckCemuProton.sh
functions/EmuScripts/emuDeckModel2.sh
functions/EmuScripts/emuDeckRyujinx.sh
functions/EmuScripts/emuDeckXenia.sh
functions/EmuScripts/emuDeckYuzu.sh
functions/ToolScripts/emuDeckESDE.sh
functions/appImageInit.sh

* If users reset emulator configurations and not ES-DE, a junk custom_systems file would be created. This adds creating the custom_systems folder to emulator scripts when applicable.
* Added a function to ES-DE to delete the junk custom_systems file so legacy users can update and have the custom_systems folder actually generate.

ES-DE: Hotfix custom_systems folder not being created

---

functions/EmuScripts/emuDeckBigPEmu.sh
functions/EmuScripts/emuDeckCemu.sh
functions/EmuScripts/emuDeckCemuProton.sh
functions/EmuScripts/emuDeckModel2.sh
functions/EmuScripts/emuDeckRyujinx.sh
functions/EmuScripts/emuDeckXenia.sh
functions/EmuScripts/emuDeckYuzu.sh

* If users delete their custom systems folder and reset an emulator, it previously would not set the paths correctly. Added ESDE_setEmulationFolder to emulator scripts when applicable.

ES-DE: Hotfix paths not being set

---

functions/EmuScripts/emuDeckPCSX2QT.sh

Onboarding wizard now shows up on launch (even though EmuDeck already configures everything). This disables the onboarding wizard by default.

PCSX2: Disable wizard by default

---

configs/pegasus-frontend/game_dirs.txt

Adding symlinks to the `game_dirs.txt` file causes duplicates to show up in Pegasus.
GC and N3DS are already mapped in the config so this is a minor/no impact change.

Pegasus: Remove symlink folders

---

configs/mame/mame.ini
functions/EmuScripts/emuDeckMAME.sh

* Set MAME back to read only. When enabled, this setting pretty much allows MAME to create copies of the original MAME INI matching the game name which can get out of control quick. Disabled is the current default on a clean MAME install.
* Added plugin folder configuration so users can download plugins.
* Added folder creation in $HOME/.mame as a fallback (if users Google MAME folders or talk to MAME support, these are what likely show up).

MAME: Hotfix INI

---

configs/org.DolphinEmu.dolphin-emu/config/dolphin-emu/Profiles/Wiimote/Wii_base_nunchuck_with_touchpad.ini
configs/org.DolphinEmu.dolphin-emu/config/dolphin-emu/Profiles/Wiimote/Wii_no_attachment_with_touchpad.ini

* Front-ends use the custom EmuDeck Steam Input profile which binds the right trackpad to left click. This PR adds support for left clicking in Wii games.

Dolphin: Hotfix trackpad support in front-ends

---

functions/EmuScripts/emuDeckCemu.sh

A broken symlink was causing Cemu to not download graphic packs.

Cemu: Hotfix graphic packs

---

functions/ToolScripts/emuDeckPegasus.sh
versions.json

* With the gc/n3ds folders, the Pegasus script was creating infinite symlinks which was causing crashing/freezing in SRM

Pegasus: Hotfix bad symlinks

---

functions/EmuScripts/emuDeckBigPEmu.sh
functions/EmuScripts/emuDeckCemuProton.sh
functions/EmuScripts/emuDeckModel2.sh
functions/EmuScripts/emuDeckRyujinx.sh
functions/EmuScripts/emuDeckXenia.sh
functions/EmuScripts/emuDeckYuzu.sh
functions/ToolScripts/emuDeckESDE.sh
functions/helperFunctions.sh

* Added rsyncing proton-launch.sh and appID.py to xenia and bigpemu so if users delete them accidentally, they have an easy way of getting fresh files.
* Moved resetting ES-DE's settings into its own function so if users reset any of the custom system emulators, they don't also have their settings reset.
* This was also causing failure in very niche cases where if users didn't have a full suite of ES-DE configs, resetting the config would also fail.
* Cleaned up functions a little for easier maintenance.
* Added detection for old ES-DE installs so resetting config on custom system emulators actually grabs the latest custom systems file.
* Split BigPEmu custom system insertion into atarijaguar and atarijaguarcd
* Adjusted custom systems insertion to be less aggressive (if resetting …

Proton Cleanup

---

functions/RemotePlayClientScripts/remotePlayGreenlight.sh
functions/RemotePlayClientScripts/remotePlayShadow.sh
tools/remoteplayclients/Greenlight.sh
tools/remoteplayclients/ShadowPC.sh
tools/remoteplayclients/Spotify.sh
tools/remoteplayclients/SteamLink.sh

* Added missing launchers for Greenlight, ShadowPC, Spotify, and Steam Link 
* If users installed these previously, these would not be added to the remoteplay folder

Remote Play Clients: Add missing launchers

---

configs/cemu/config/cemu/settings.xml

This was added in the most recent update of Cemu, enable by default so users can easily update Cemu.

Cemu: Enable auto-updater

---

functions/EmuScripts/emuDeckRetroArch.sh

* This was creating infinite symlinks, commented out and delete the folders for now. Can re-add in the future after more testing.
* Reverted texture pack path settings, this was causing an increase in graphical issues in RA's N64 core.

RetroArch: Hotfix N64 texture pack paths

---

tools/launchers/cemu.sh

* Users keep selecting the Proton ver of Cemu in Steam ROM Manager and ES-DE, this increases support requests in the Cemu Discord (which they can't fix) and support requests in the EmuDeck Discord. This bandaid falls back to the AppImage if the EXE does not exist.

Cemu: Hotfix Proton headaches

---

configs/steam-input/emudeck_controller_generic.vdf
configs/steam-input/emudeck_controller_ps4.vdf
configs/steam-input/emudeck_controller_ps5.vdf
configs/steam-input/emudeck_controller_ps5_dualsense_edge.vdf
configs/steam-input/emudeck_controller_steamcontroller.vdf
configs/steam-input/emudeck_controller_steamdeck.vdf
configs/steam-input/emudeck_controller_steamdeck_radial_menus.vdf
configs/steam-input/emudeck_controller_switch_pro.vdf
configs/steam-input/emudeck_controller_xbox360.vdf
configs/steam-input/emudeck_controller_xboxelite.vdf
configs/steam-input/emudeck_controller_xboxone.vdf
configs/steam-input/emudeck_frontend_controller_generic.vdf
configs/steam-input/emudeck_frontend_controller_ps4.vdf
configs/steam-input/emudeck_frontend_controller_ps5.vdf
configs/steam-input/emudeck_frontend_controller_ps5_dualsense_edge.vdf
configs/steam-input/emudeck_frontend_controller_steamcontroller.vdf
configs/steam-input/emudeck_frontend_controller_steamdeck.vdf
configs/steam-input/emudeck_frontend_controller_switch_pro.vdf
configs/steam-input/emudeck_frontend_controller_xbox360.vdf
configs/steam-input/emudeck_frontend_controller_xboxelite.vdf
configs/steam-input/emudeck_frontend_controller_xboxone.vdf
configs/steam-input/emudeck_steam_deck_light_gun_controls.vdf
configs/steam-rom-manager/userData/controllerTemplates.json
configs/steam-rom-manager/userData/userConfigurations.json
functions/ToolScripts/emuDeckSRM.sh

* Controller templates did not have localization names set properly causing them to unstick in Steam ROM Manager/identify as another controller profile 
* Updated controllerTemplates.json file to match changes
* Updated Steam path to ~/.local to match new SRM update

Steam ROM Manager: Hotfix controller templates

---

functions/EmuScripts/emuDeckLime3DS.sh

lime3ds-gui file was renamed to just lime3ds (v2118) so this handles that.
`Lime3DS_emuPath` (lime3ds-gui) left as is so es-de can still find it - could be updated in the future

Fix Lime3DS AppImage Filename

---

functions/EmuScripts/emuDeckRyujinx.sh
functions/helperFunctions.sh
tools/launchers/ryujinx.sh

- fix launcher not finding flatpak
- improve finding correct GH asset (fileNamestartsWith) - different asset order on GH would download wrong one as they all end the same)

fix: Ryujinx launcher for Flatpak

---

configs/net.shadps4.ShadPS4/config/shadps4/config.toml
configs/net.shadps4.ShadPS4/config/shadps4/inputConfig/default.ini
configs/steam-deck-romate/userConfigurations.json
functions/EmuScripts/emuDeckShadPS4.sh
functions/ToolScripts/emuDeckMigration.sh
functions/all.sh
functions/helperFunctions.sh
functions/jsonToBashVars.sh
settings.sh
setup.sh
uninstall.sh
versions.json

Addressing issue #1309, this PR is a draft I created in my best ability to help push the [ShadPS4 Flatpak](https://github.com/shadps4-emu/shadPS4-flatpak) for inclusion in the Emudeck.
Please feel free to criticize this PR as I am new to this project. I have the flatpak install function as a TODO in the comments.
┆Issue is synchronized with this [Trello card](https://trello.com/c/7igLxQ33) by [Unito](https://www.unito.io)

Added ShadPS4 Flatpak

---

configs/steam-deck-romate/userConfigurations.json
configs/steam-rom-manager/userData/parsers/emudeck/sony_psvita-vita3k-pkg.json
configs/steam-rom-manager/userData/userConfigurations.json
functions/EmuScripts/emuDeckRyujinx.sh
functions/EmuScripts/emuDeckShadPS4.sh
functions/EmuScripts/emuDeckXenia.sh
functions/helperFunctions.sh
functions/installEmuAI.sh
tools/emu-launch.sh
tools/generic-applications/Heroic-Games-Launcher.sh
tools/launchers/shadps4.sh
tools/launchers/yuzu.sh
tools/remoteplayclients/Greenlight.sh
tools/remoteplayclients/ShadowPC.sh
tools/remoteplayclients/chiaki-ng.sh
tools/savesync.sh

ShadPS4
- separate download/unzip/AppImage setup when installing; download zip first, then unzip and then do AppImage things (installEmuAI)
- create bios link for LLE sys_modules (optional)
- launcher: we can use variables from emu script
- launcher: fallback to flatpak handled more gracefully
- launcher: better handling of .desktop file arguments
Ryujinx
- currently, the "nogui" version is downloaded; it doesn't make a difference but it might later; implement fileNameDoesNotContain in getReleaseURLGH helper function and make use of it for Ryu
Xenia
- latest version is running fine, removed hardcoded release

Couple of fixes (ShadPS4, Ryujinx, Xenia)

---

configs/cemu/config/cemu/settings.xml

Fixed a bug in Cemu that brakes the blow mic button, input device is experimental so it doesn't function on any device I tested (Steamdeck and Windows)
Setting this line to empty disables the input and blow mic functions normally
EmuDeck is a free open source project, but we have an Early Access tier on Patreon where people can get timely exclusive to some features.
Do you allow us to merge this PR to the Early Access branch, or do you only want your work to be available when the next public build is released?
- [-] I've tested and verified that the PR works in at least one device.
I've tested the setting manually and copied to another installation to test and it works, I assume emudeck copies only the file so it should work

Cemu: Disable input for blow mic hotkey

---

chimeraOS/configs/emulationstation/custom_systems/es_find_rules.xml

This adds an ES-DE find rule so that the version of Dolphin installed by EmuDeck is launched on ChimeraOS.  This fixes an issue where the version of Dolphin provided by ChimeraOS can be launched instead, resulting in the EmuDeck configs and settings not being used.
Fixes #1405

Add ES-DE find rule for Dolphin on ChimeraOS

---

configs/steam-rom-manager/userData/userConfigurations.json

Fix Cemu invalid in SRM : userConfigurations.json
fix the line 4059 and 4186 :
"long": "/home/deck/.config/EmuDeck/backend/configs/steam-rom-manager/userData/img/systems/grid/wiiu.jpg",
-> dosnt exist anymore . 
Generates invalid emulator in SRM .

Fix_Cemu_SRM_userConfigurations.json

---

configs/steam-input/emudeck_controller_steamdeck_radial_menus.vdf

following my search in the issue https://github.com/dragoonDorise/EmuDeck/issues/1451
some keys / button seems to no be mapped according to the ini provided : 
adial Menu Citra :
Special touch_menu_button_7 X:key to Exit Not working
Also
Missing back buttons
F key toggle full screen = L4 --- ini Shortcuts\Main%20Window\Fullscreen\KeySeq=F11
E key layout toggle = L5 -------- ini Shortcuts\Main%20Window\Toggle%20Screen%20Layout\KeySeq=Tab
S key Swap screen = R4 ---------- ini Shortcuts\Main%20Window\Swap%20Screens\KeySeq=Ctrl+Tab
X key Quit = R5 ----------------- ini Shortcuts\Main%20Window\Exit%20Citra\KeySeq=Alt+F4
So i applied right mapping in steam and exported the lines changed to add it in the main repo.
Then i downloaded the modified VDF and tested it with Azahar appimage throught …

Fix Azahar -  ESDE Radial menu and backbuttons

---

tools/appID.py

We can save some lines, plus best practice is referencing sys.argv in __main__ block only.

Remove main function from appID.py

---

configs/emulationstation/custom_systems/es_find_rules.xml

Ive noted an issue using this  find rules file . 
the cores path given point to non-existent directory for the cores: 
```
<core name="RETROARCH">
<rule type="corepath">
<entry>~/.config/retroarch/cores</entry>
```
https://github.com/dragoonDorise/EmuDeck/blob/main/configs/emulationstation/custom_systems/es_find_rules.xml
But according to the emucsript of retroarch : 
`RetroArch_cores="$HOME/.var/app/org.libretro.RetroArch/config/retroarch/cores"`
https://github.com/dragoonDorise/EmuDeck/blob/main/functions/EmuScripts/emuDeckRetroArch.sh
For example here is a result using with this find rule : ~/.config/retroarch/cores ;
I tried for various system using cores and always will results error not found : 
```
Apr 20 12:45:19 Info:   Launching game "2020 Super Baseball" from system "SNK Neo …
```

Fix retroarch cores in es_find_rules.xml

---

store/gbc/Himes Quest.json

This image is broken url causing interface to be blank. This PR fixes the image url to match the existing image file.

chore: Fix broken image url for game
